# Generated by Django 4.2.8 on 2023-12-15 17:38

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    replaces = [('blog', '0001_initial'), ('blog', '0002_alter_article_image'), ('blog', '0003_auto_20220117_1548'), ('blog', '0004_article_author_alter_article_created_and_more'), ('blog', '0005_alter_article_image'), ('blog', '0006_alter_article_image'), ('blog', '0007_alter_article_author_comment'), ('blog', '0008_alter_article_image'), ('blog', '0009_alter_article_image')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, default='Cat03.jpg', null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('author', models.EmailField(blank=True, max_length=100, null=True)),
            ],
            options={
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.EmailField(blank=True, max_length=100, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
