# Generated by Django 5.0 on 2023-12-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_squashed_0009_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='DEFAULT', max_length=100),
        ),
    ]
